### PR TITLE
Feature/AD-28 Enhanced Search Filtering

### PR DESCRIPTION
**Pull request by garethdandrews**
Categories have been added to the projects index page to allow for better sorting of the resources, including search results, by Recent (most recent), Popular (most liked), and Discussed (most comments). These metrics can be revised later.

Screenshot 2021-08-31 at 13 11 42
Screenshot 2021-08-31 at 13 13 48

In this PR I've also added a container to the home page that includes a search bar and a button to the projects index page, which I think improves the flow of the application.

Screenshot 2021-08-31 at 13 14 12

### CODE REVIEW

**Comment by IeuanSkinner** [comment]
Just to correct the PR description it's most recent, most popular (which means most liked) and most discussed (most comments) right?

**Comment by garethdandrews** [comment]
@IeuanSkinner yeah correct. I should've made it clearer instead of saying 'respectively'.

**Comment by garethdandrews** [comment]
@IeuanSkinner Updated the description.

**Review by AlexW555 — APPROVED** [review]
Looks good, I like the sign-in link included in the text too

**Comment by garethdandrews** [comment]
All changes that were discussed in yesterday's meeting have been made. I have quickly tested to see if I can inject a simple script tag into the markdown editor, and I was unable to. From reading online, it looks like there were XSS fixes in version > 1.2.2. 
https://snyk.io/vuln/SNYK-JS-TRIX-536207

**Pull request merged**
